services:
  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb
    command: keydb-server /etc/keydb/keydb.conf --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./keydb-data:/data  # Persist KeyDB data to a local directory in the project root

  auth_service:
    build:
      context: .  # Set context to the project root
      dockerfile: ./auth_service/Dockerfile
    container_name: auth_service
    volumes:
      - ./logs:/app/logs  # Bind the logs directory to the host system
    env_file:
      - .env.docker
    depends_on:
      - keydb

volumes:
  keydb-data:
