services:
  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb
    command: keydb-server /etc/keydb/keydb.conf --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./keydb-data:/data  # Persist KeyDB data to a local directory in the project root

  rediscommander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    ports:
      - "8083:8081"  # Map Redis Commander to port 8083 on the host
    environment:
      - REDIS_HOSTS=local:keydb:6379  # Point to the KeyDB service
    depends_on:
      - keydb
    restart: always

  sense_pro_server:
    build:
      context: .  # Set context to the project root
      dockerfile: ./Dockerfile
    container_name: sense_pro_server
    volumes:
      - ./logs:/app/logs  # Bind the logs directory to the host system
    env_file:
      - .env.docker
    depends_on:
      - keydb

volumes:
  keydb-data:
