services:
  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb
    command: keydb-server /etc/keydb/keydb.conf --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./keydb-data:/data  # Persist KeyDB data to a local directory in the project root

  rediscommander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    ports:
      - "8083:8081"  # Map Redis Commander to port 8083 on the host
    environment:
      - REDIS_HOSTS=local:keydb:6379  # Point to the KeyDB service
    depends_on:
      - keydb
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user  # Default username
      RABBITMQ_DEFAULT_PASS: password  # Default password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  keydb-data:
  rabbitmq_data:
